### ISSUE TITLE
AttributeError when using requests_mock.mock() with requests_cache

### ISSUE THREAD

**Issue by skinderis** [reclosedev/requests-cache#226] opened 2021-04-12 10:08 UTC
### The problem

Hey, several days ago requests-cache was updated from 0.5.2 version to 0.6.0 version and my python unittests started failing. Was running unittests where mocked requests are included and getting this error:

```
*** AttributeError: 'Response' object has no attribute 'from_cache'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests_cache/session.py", line 101, in request
    if not response.from_cache and not self.filter_fn(response):

```

### Expected behavior
_A description of what you expected to happen_

requests.get() should return mocked value as it was returning before.

### Steps to reproduce the behavior
_With a complete code example, if possible_

```
import requests
import requests_mock

url = X

with requests_mock.mock() as mock:
    mock.get(url, text={'response': 'very good'})
    run_function(mock)
    requests.get(X).json()
```

### Workarounds
_Is there an existing workaround for this issue?_

No, just switching back to 0.5.2 version works.

### Environment
- requests-cache version: 0.6.2
- Python version: 3.8.2
- requests-mock: 1.8.0
- requests: 2.24.

**Comment by JWCook** [comment] 2021-04-12 15:33
Looks like there are a couple different things going on here. I could update `CachedSession.request` to suppress that error if you just need a short-term fix, but I think that error is actually useful in this case because it indicates that the cache isn't being used as expected.

The main issue is that there's a bit more setup required to get `requests-mock` and `requests-cache` to work together. In your code example, you're correct that `requests-cache 0.5.x` won't raise an error there, but it also won't be working as intended. Basically that `requests_mock.mock()` contextmanager is going to patch `Session.send()`, which partially overrides the patching done by `requests_cache.install_cache()`. So `CachedSession.send()` will never get called, which is why `response.from_cache` isn't set, and why the response won't actually get cached.

There are more details in #87 and #158, and there's an example of using both caching and mocking together in the docs here: https://requests-cache.readthedocs.io/en/latest/advanced_usage.html#requests-mock

Give that a try, and let me know if that works for you.

**Comment by JWCook** [comment] 2021-04-17 01:59
@skinderis Did this answer your question, or are you still having issues getting requests-cache and requests-mock to work together?

**Comment by JWCook** [comment] 2021-04-20 16:13
I'm going to close this issue for now, but let me know if you have more questions and I can reopen it.

**Closed by JWCook** 2021-04-20 16:13 UTC
