### ISSUE TITLE
File system backend

### ISSUE THREAD

**Issue by julienfr112** [reclosedev/requests-cache#109] opened 2018-06-19 20:07 UTC
What about a file backend ? In the style of what you get when you do a wget --recursive ?

It could also be effective to compress the data, who are often very similar when you scrap a web site, by using a zip file containing the files with the same tree.

**Comment by codypiersall** [comment] 2018-06-21 15:08
This looks like the same issue as #30.  I too would like to see something like this!

**Comment by codypiersall** [comment] 2018-06-24 03:04
I have an implementation for [a project I'm working on](https://github.com/codypiersall/vismap/blob/master/vismap/fs_cache.py).  I have a feeling there are some corner cases I hadn't considered, which is why I'm not submitting a PR.  But maybe this can be a starting point for someone else.

**Comment by JWCook** [comment] 2021-02-24 23:48
Closing this as a duplicate of #30 .

Looks like there was a PR for this submitted a few years ago: https://github.com/reclosedev/requests-cache/pull/97 @julienfr112 @codypiersall If you or someone else would still like this feature, please resubmit that as a new PR, and I can review and merge it.

**Closed by JWCook** 2021-02-24 23:48 UTC
Labels: duplicate, enhancement
