### ISSUE TITLE
etag only caching + remove_expired_responses()

### ISSUE THREAD

**Issue by lazka** [reclosedev/requests-cache#620] opened 2022-04-30 12:37 UTC
Using 0.10.0.dev4 with sqlite

From what I understand this version now supports etag only caching, so cache-control gets ignored and things get cached and re-validated the next time.

Problems:

* How do I keep the size of the cache file in check if there is no expiration date anymore? remove_expired_responses() doesn't do anything in that case from what I see.
* If I call remove_expired_responses() with an expiration date it will mutate the existing cache, so future requests will no longer re-validate via etag. Imo a bug.

Just a wild guess, but maybe the cache should store when the cache entry was created, or last used, and remove_expired_responses() could gain an additional parameter where one can say "delete everything that is more than X days old" or "delete everything that hasn't been used in X days"

**Comment by JWCook** [comment] 2022-04-30 15:35
> From what I understand this version now supports etag only caching, so cache-control gets ignored and things get cached and re-validated the next time.

ETags have been supported since 0.8. Have you noticed any different behavior in the current pre-release build? Assuming you're creating your session with `cache-control=True`, Cache-Control headers aren't ignored, and  they will still set an expiration value. But if there is also a validator (ETag or Last-Modified), yes, the response will be saved and re-validated when expired. `Cache-Control: no-store` will skip writing to the cache even if there's a validator, though. That's roughly the same behavior as browser caches.

>  remove_expired_responses() doesn't do anything in that case from what I see.

That's definitely not the intended behavior. Can you give me a code example to reproduce this?

Here's an example using the GitHub API to get details about this repo, which returns both ETag and Cache-Control headers:
```python
from datetime import datetime
from time import sleep
from requests_cache import CachedSession

# Get an initial response and then retrieve it again from the cache
session = CachedSession(cache_control=True)
url = 'https://api.github.com/repos/reclosedev/requests-cache'
r = session.get(url)
r = session.get(url)

# Wait until it's expired
print(r.headers)
expires_in_seconds = (r.expires - datetime.utcnow()).total_seconds()
print(f'Expires: {r.expires} ({expires_in_seconds:.1f}) seconds')
sleep(expires_in_seconds)

# Remove expired responses and verify that it's no longer in the cache
print('Total cached responses:', len(session.cache.responses))
print('URL in cache:', session.cache.has_url(url))
session.remove_expired_responses()
print('Total cached responses:', len(session.cache.responses))
print('URL in cache:', session.cache.has_url(url))
```

**Comment by lazka** [comment] 2022-04-30 16:14
So we are on the same page, here is what I do:

* I'm in fact using this for the github API (via pygithub)
* I need validation-only caching for the github API to reduce bandwith as well as rate-limiting
* github also sends `cache-control: public, max-age=60, s-maxage=60` but I actively change resources and caching would result in race conditions.

I've tried to point out the issues in inline-comments:

```python
from logging import basicConfig, getLogger
from requests_cache import CachedSession
from datetime import datetime

basicConfig(level='INFO')
getLogger('requests_cache').setLevel('DEBUG')
session = CachedSession(cache_control=False, expire_after=0)
url = 'https://api.github.com/repos/reclosedev/requests-cache'

r = session.get(url)
# in 0.9 this didn't hit the cache, in 0.10 it does and I can now use you library :)
r = session.get(url)

expires_in_seconds = (r.expires - datetime.utcnow()).total_seconds()
print(expires_in_seconds)

# this doesn't remove, but it also shouldn't I guess,
# since the cache entry is used for validation in the future,
# and there is no inherent expiration date
session.cache.remove_expired_responses()

# now for bug:

session.cache.remove_expired_responses(1000)
# this doesn't send a validation request anymore.. same for all future requests for the same URL
# somehow the removal has modified the cache behaviour..
r = session.get(url)
```


I've now worked this around by doing this once in a while:

```python
if session.cache.response_count() > 200:
    session.cache.clear()
```

**Comment by JWCook** [comment] 2022-04-30 17:34
> 
```python
# this doesn't remove, but it also shouldn't I guess,
# since the cache entry is used for validation in the future,
# and there is no inherent expiration date
session.cache.remove_expired_responses()
```
Oh, interesting. You found a very specific bug that occurs with the combination of SQLite backend, `cache_control=False`, `expire_after=0`, and `remove_expired_responses()`. The response _should_ be removed in this case, since you set `expire_after=0` on the session, and `remove_expired_responses()` is supposed to remove all expired responses regardless of whether they could be revalidated or not. It looks like this behavior changed in #573.

>
```python
session.cache.remove_expired_responses(1000)
# this doesn't send a validation request anymore.. same for all future requests for the same URL
# somehow the removal has modified the cache behaviour..
```

This call says "reset expiration for all responses to 1000 seconds in the future." It's relative to the current date/time. I agree that it would be useful to have a separate option to do this relative to the created date instead ("delete everything that is more than X days old"). The created date is already stored in the cache (`CachedResponse.created_at`), so this wouldn't be too difficult to add.

I just tested this example, and if you wait another 1000 seconds for the response to expire, it will be revalidated. Conditional requests are only sent when a response expires, so it looks like this is working as intended. If you want to revalidate for every request, your settings of `CachedSession(cache_control=False, expire_after=0)` will do what you want.

**Comment by JWCook** [comment] 2022-04-30 17:36
> I've now worked this around by doing this once in a while:
```python
if session.cache.response_count() > 200:
    session.cache.clear()
```

Okay, this makes more sense now. So you want to
* keep a fairly small cache
* revalidate for every request
* keep _recent_ expired responses to reuse for revalidation
* occasionally delete responses older than some value

I think the combination of "small cache" and "validation only" is the tricky part. If you just want to keep a small cache, Cache-Control (or expire_after) + `remove_expired_responses()`  will work. If you just want validation-only, `expire_after=0` will work. If you want both, I think the ideal feature for your use case would be an LRU or LFU cache (#116). I don't currently have plans to implement that, but the next best thing would be what you described in your first post, an option to "delete everything that is more than X days old." Do you think that would be sufficient?

And since you're using the pre-release build, there is one other option that works currently:
```python
r = session.get(url, refresh=True)
```

`refresh=True` is a "soft refresh," basically the same as F5 in a browser. It will force revalidation even if the cached response isn't expired. I could possibly add a `CachedSession` option to do that for every request, if that would be helpful. Then that would let you set an expiration value (either via GitHub's Cache-Control or expire_after), ignore that expiration when you're making requests so you always revalidate, and then use it only for `remove_expired_reponses()`.

**Comment by lazka** [comment] 2022-05-01 15:33
> > I've now worked this around by doing this once in a while:
> 
> ```python
> if session.cache.response_count() > 200:
>     session.cache.clear()
> ```
> 
> Okay, this makes more sense now. So you want to:
> 
>     * Keep the cache fairly small

Not necessarily small, just any kind of bounds. I was planning to store it in the github actions CI cache, and there it would grow indefinitely without intervention.

>     * Revalidate for every request (e.g., everything "expires immediately")
> 
>     * Keep _recent_ expired responses to reuse for revalidation
> 
>     * Occasionally delete responses older than some value
> 
> 
> I think the combination of "small cache" and "validation only" is the tricky part. If you just want to keep a small cache, Cache-Control (or expire_after) + `remove_expired_responses()` will work. If you just want validation-only, `expire_after=0` will work. If you want both, I think the ideal feature for your use case would be an LRU or LFU cache (#116). I don't currently have plans to implement that, but the next best thing would be what you described in your first post, an option to "delete everything that is more than X days old." Do you think that would be sufficient?

tbh, I'm actually fine with my workaround right now :) but yes I think that would be sufficient.

> And since you're using the pre-release build, there is one other option that works currently:
> 
> ```python
> r = session.get(url, refresh=True)
> ```
> 
> `refresh=True` is a "soft refresh," basically the same as F5 in a browser. It will force revalidation even if the cached response isn't expired. I could possibly add a `CachedSession` option to do that for every request, if that would be helpful. Then that would let you set an expiration value (either via GitHub's Cache-Control or expire_after), ignore that expiration when you're making requests so you always revalidate, and then use it only for `remove_expired_reponses()`.

I think that sounds reasonable. In my case I use the ugly monkey patching because of pygithub, so it'd have to be a global option.

**Comment by JWCook** [comment] 2022-05-04 03:51
Changes from #624 are in the master branch, if you want to try them out. You can pass the new `always_revalidate` argument (and any other `CachedSession` arguments) to `install_cache()`.

> I think that sounds reasonable. In my case I use the ugly monkey patching because of pygithub, so it'd have to be a global option.

Yeah, if you have any ideas for improving that, I'm definitely open to suggestions. The best-case scenario for using requests-cache with other libraries that use `requests` is if:
A) the library lets you pass your own session object, or
B) the library provides its own session class that you can subclass ([examples](https://requests-cache.readthedocs.io/en/stable/user_guide/compatibility.html)).

Maybe the PyGithub maintainers would be open to a PR to allow passing your own session?

When that isn't possible, sometimes you can do a more targeted monkey-patch, which isn't any less ugly (actually more so 🤢), but lets you cache only requests from that library without affecting other requests. In the case of PyGithub, you can patch [`github.Requester.Requester.__httpsConnectionClass`](
https://github.com/PyGithub/PyGithub/blob/001970d4a828017f704f6744a5775b4207a6523c/github/Requester.py#L202). On a `github.Github` object, that would be `<object>._Github__requester._Requester.__connectionClass` ([example here](https://github.com/reclosedev/requests-cache/issues/332#issuecomment-900181721)).

**Comment by JWCook** [comment] 2022-05-04 04:37
> I was planning to store it in the github actions CI cache

That's a good idea, I haven't tried that before. Would that just use the built-in [cache action](https://github.com/actions/cache) to store your SQLite db? A config snippet for that might make a good addition to the [examples/](https://github.com/reclosedev/requests-cache/tree/master/examples) folder, if you'd be interested in adding that sometime.

**Comment by JWCook** [comment] 2022-05-15 03:13
I'm going to go ahead and close this, but let me know if you have any other problems or suggestions.

**Closed by JWCook** 2022-05-15 03:13 UTC
Labels: bug, enhancement
