### ISSUE TITLE
Add normalization for request json argument

### ISSUE THREAD

**Issue by gwillem** [reclosedev/requests-cache#154] opened 2020-05-14 09:33 UTC
Caching doesn't seem to work when using the `json=` argument to `requests.post`. Presumably, because the request key is calculated on the body (after the `json` argument has been serialized). Am not sure how to fix, other than not using the `json` auto serialization.

**Comment by dbr** [comment] 2020-05-30 07:42
Doesn't seem to be documented to clearly, but if you include `include_get_headers=True` in your CachedSession args the requests headers will be included in the cache key, e.g

```python
self.session = requests_cache.CachedSession(
    ...
    include_get_headers=True,
)
```

Was added in #6

**Comment by gwillem** [comment] 2020-05-30 10:46
Thanks! But how would that influence the POST body?

**Comment by dbr** [comment] 2020-05-31 04:55
Ah, sorry, may not be relevant! I was confused by some of our code which is working as intended using the `.post(json=...)` arg, but.. it was also using the `headers=...` arg too which was the important part here

The code which calculates the cache key here:
https://github.com/reclosedev/requests-cache/blob/6717a336430eb7e6fe17e75c5517f3076ca85b42/requests_cache/backends/base.py#L218-L233

On first glance it seems like this includes `request.body` which I'm assuming is
https://requests.readthedocs.io/en/master/api/#requests.PreparedRequest
which sounds like it should include the serialised JSON body - so would probably need more investigation as to why the POST body isn't being included

**Comment by JWCook** [comment] 2021-02-26 23:04
Yeah, `PreparedRequest.body` would include content from either `Request.data` or `Request.json`.

Example:
```python
import requests

>>> request_1 = requests.Request('POST', 'https://httpbin.org/get', data={'foo': 'bar'})
>>> request_1.prepare().body
'foo=bar'

>>> request_2 = requests.Request('POST', 'https://httpbin.org/get', json={'foo': 'bar'})
>>> request_2.prepare().body
b'{"foo": "bar"}'
```

So this one will take a little more digging.

**Comment by FredHappyface** [comment] 2021-03-04 02:03
This seems to be an issue when stringifying json and passing to data too

```py
requests_cache.install_cache("github_graph",
"sqlite",
60 * 60 * 12, (200), ("GET", "POST"),
include_get_headers=True)

...

request = requests.post("https://api.github.com/graphql",
data=dumps({"query": query}).encode('utf-8'),
headers={"Authorization": "bearer " + getPassword()})

```

**Closed** 2021-03-30 23:04 UTC
Labels: bug, help-wanted
