### ISSUE TITLE
Do not invalidate cache if update fails

### ISSUE THREAD

**Issue by sharkone** [reclosedev/requests-cache#40] opened 2015-01-20 05:55 UTC
Hi,

I started using your great library and had an idea. Right now it seems that when the cache of a request is found expired, we immediately delete it and try to update it right away, but this could eventually fail, leaving us with no data at all. Would it be possible to only delete the existing cache if the update is successful? This way we could still rely on older data.

Looking at the code in core.py lines 103-104, this looks like a trivial change. This behavior could even be optional.

What do you think?

**Comment by reclosedev** [comment] 2015-01-20 19:06
Hi,

Not sure about that. I think If some response is expired, code shouldn't relay on it anymore.
Maybe I don't fully understand your case?

**Comment by sharkone** [comment] 2015-01-20 19:10
Hi and thanks for your answer.

I use requests_cache to cache some metadata (summary, images...) about movies from [Trakt.tv](http://trakt.tv). I try to get fresh data as much as possible but I can live with older data if updating fails.

**Comment by reclosedev** [comment] 2015-01-20 19:24
> if updating fails.

Do you mean response with non OK code or problems with storage backend? 
Maybe we can add this as an optional behaviour.

**Comment by sharkone** [comment] 2015-01-20 19:25
Well, any kind of problems really, either on the server side or the cache side.

**Comment by reclosedev** [comment] 2015-01-20 19:50
Something like this:
```python
        if self._cache_expire_after is not None:
            is_expired = datetime.utcnow() - timestamp > self._cache_expire_after
            if is_expired:
                if not self._return_old_data_on_error:
                    self.cache.delete(cache_key)
                    return send_request_and_cache_response()
                try:
                    new_response = send_request_and_cache_response()
                except Exception:
                    return response
                else:
                    if new_response.status_code not in self._cache_allowable_codes:
                        return response
                    return new_response
```
Need mock to cover it by tests.

**Comment by sharkone** [comment] 2015-01-20 19:52
That's pretty much what I had in mind. What's the next step then?

**Comment by reclosedev** [comment] 2015-01-20 21:18
Committed, added test, but it fails. I'll try to fix it tomorrow or later.

**Comment by reclosedev** [comment] 2015-02-02 18:31
Sorry for no updates, busy days on work. Also, I can't reproduce travis failures locally.

**Closed** 2016-03-19 07:54 UTC
