### ISSUE TITLE
`AttributeError`: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by lmmarsano** [reclosedev/requests-cache#420] opened 2021-09-20 07:15 UTC
### The problem
`POST` request containing JSON results in this error with traceback containing
```
../../.pyenv/versions/3.9.6/envs/ear/lib/python3.9/site-packages/requests_cache/session.py:120: 
../../.pyenv/versions/3.9.6/envs/ear/lib/python3.9/site-packages/requests_cache/cache_keys.py:159: 
../../.pyenv/versions/3.9.6/envs/ear/lib/python3.9/site-packages/requests_cache/cache_keys.py:173: AttributeError
```

The offending code appears to be
https://github.com/reclosedev/requests-cache/blob/5605db4a84c4ee15f4406ea872aa650e31f3348f/requests_cache/cache_keys.py#L156-L178
where `items` serialized JSON text.
In a debugger session, I notice data that is both `str` & `Mapping`.
```python
(Pdb) tbreak ../../.pyenv/versions/3.9.6/envs/ear/lib/python3.9/site-packages/requests_cache/cache_keys.py:159
Breakpoint 1 at /home/LOM0227/.pyenv/versions/3.9.6/envs/ear/lib/python3.9/site-packages/requests_cache/cache_keys.py:159
>>>>>>>>>>> PDB continue (IO-capturing resumed) >>>>>>>>>>>>
> /home/LOM0227/.pyenv/versions/3.9.6/envs/ear/lib/python3.9/site-packages/requests_cache/cache_keys.py(159)normalize_dict()
-> return sort_dict(items)
(Pdb) p items
'{"searchText": "dt.redacted.com NOT (ext:html OR ext:md)", "$skip": 0, "$top": 1000}'
(Pdb) p isinstance(items, Mapping)
True
(Pdb) p issubclass(str, Mapping)
True
```

### Expected behavior
Request to go through.

### Environment
- requests-cache==0.8.0
- python 3.9.6
```shellsession
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute
```

**Comment by JWCook** [comment] 2021-09-20 17:02
Hmm, there must be something else going on here. `str` is not a `Mapping`, and `Mapping` by definition has a `.items()` method. I tried to reproduce your example in PDB in python 3.9.6:
```python
(Pdb) from typing import Mapping
(Pdb) p isinstance('some string', Mapping)
False
(Pdb) p issubclass(str, Mapping)
False
```

Also, there are automated tests for POST with serialized request body that would have caught this. I can update `normalize_dict()` with an extra sanity check, but I'd like to understand the problem first.

Could you provide a complete code sample that reproduces this, and a full traceback?

**Comment by lmmarsano** [comment] 2021-09-23 02:44
Apologies: the issue occurred in a private repo, and it took me some time write [a reduced reproduction](https://github.com/lmmarsano/requests-cache-demo).
The root cause wasn't immediately obvious to me, and I don't think this library could reasonably be expected to do much about it.
I attempted to [define immutable, hashable mappings](https://github.com/lmmarsano/requests-cache-demo/blob/c463dcf3e701c2938ac778ab641542141987df64/src/requests_cache_demo/model.py#L23-L37) like the standard [collection abstract base classes](https://docs.python.org/3/library/collections.abc.html), by defining it to require the same required special methods as `Hashable`, `Mapping`, & `Collection`.
It also registered any class with those required methods as [a virtual subclass](https://docs.python.org/3/library/abc.html#abc.ABCMeta.__subclasshook__).
Coincidentally, `str` has all those required methods: it's hashable, immutable, and includes the minimal special methods needed to define a mapping.
Defining that class unexpectedly made `str` a `Mapping`.

Before I knew this, the error looked like a mistaken statement order in this library, which I simply 'fixed' by [changing the order](https://github.com/lmmarsano/requests-cache-demo/blob/c463dcf3e701c2938ac778ab641542141987df64/src/requests_cache_demo/vendor_patch.py#L30-L39):

1. check for text first
2. then check for mapping

I'm not sure this change is worth implementing anymore, since I doubt [defining an abstract base class like this](https://github.com/lmmarsano/requests-cache-demo/blob/c463dcf3e701c2938ac778ab641542141987df64/src/requests_cache_demo/model.py#L23-L37) is commonly done.
Sincerest apologies on reporting this prematurely: it honestly looked like a bug in the library.

**Comment by JWCook** [comment] 2021-09-23 03:47
Interesting! No worries, there's no harm in reporting something that looks like a bug. I'll go ahead and close this issue, but feel free to open another one if you run into more problems.

As for your `HashableMapping` ABC, you could consider checking for the other read-only `Mapping` methods in your `__subclasshook__`:
```python
class HashableMapping(CA.Mapping[_V_contra, _V_co], CA.Hashable, metaclass=A.ABCMeta):
  """Immutable, hashable mapping."""
  @classmethod
  def __subclasshook__(cls, other_class: type):
    """Any hashable mapping class is a subclass."""
    return (
      cls is HashableMapping
      and True == CA.Hashable.__subclasshook__(other_class) # type: ignore
      and True == CA.Collection.__subclasshook__(other_class) # type: ignore
      and True == check_methods(other_class, '__getitem__', '__eq__', '__ne__', 'keys', 'items', 'values', 'get')
      or NotImplemented
    )
```

**Closed by JWCook** 2021-09-23 03:47 UTC
Labels: bug
