### ISSUE TITLE
How to skip reading from the cache / ignore an existing cached response

### ISSUE THREAD

**Issue by johnraz** [reclosedev/requests-cache#531] opened 2022-02-16 08:59 UTC
### The problem
This is a follow up of #526, there are more failing use cases related to overriding `expire_after`.
See the code example comments for more infos.

### Expected behavior
See the code example comments for more infos.

### Steps to reproduce the behavior
```
>>> from requests_cache import CachedSession

>>> session = CachedSession(in_memory=True, expire_after=10)

>>> response = session.get('https://httpbin.org/get', expire_after=-1)

>>> print(response)
<Response [200]>

>>> response = session.get('https://httpbin.org/get', expire_after=-1)

>>> print(response)
request: GET https://httpbin.org/get, response: 200 (349 bytes), created: 2022-02-16 09:36:24 CET, expires: N/A (fresh)

# I would expect this call to use the default specified in the session and go to the network
>>> response = session.get('https://httpbin.org/get')

>>> print(response)
request: GET https://httpbin.org/get, response: 200 (349 bytes), created: 2022-02-16 09:36:24 CET, expires: N/A (fresh)

# I would expect this one to go to the network as well as it should expire after 1 sec from the created date of the currently cache response.
>>> response = session.get('https://httpbin.org/get', expire_after=1)

>>> print(response)
request: GET https://httpbin.org/get, response: 200 (349 bytes), created: 2022-02-16 09:36:24 CET, expires: N/A (fresh)


# This one works as expected 🎉 
>>> response = session.get('https://httpbin.org/get', expire_after=0)

>>> print(response)
<Response [200]>
```

### Workarounds
Not that I can think of.

### Environment
- requests-cache version: `0.9.2`
- Python version: `3.8.12`
- Platform: MacOS

**Comment by JWCook** [comment] 2022-02-16 16:49
This appears to be working as intended, but I think I understand what you want to do.

Once a response is cached, subsequent requests will use that cached response until it expires or is explicitly removed with  `session.cache.clear()`. So in your example, the initial request with `expire_after=-1` is stored indefinitely, and the subsequent requests use that instead of saving a new cached response with the new `expire_after` values you provide.

So basically, `expire_after` only applies to new cached responses. I could probably add some more details about that to the docs. The only exception, as you've found, is `0`, which skips both reading from and writing to the cache.

It sounds like what you want is an option to skip reading from the cache, so you get a new response from the network and cache it with whatever expiration you provide. Is that correct? If so, I think you're the second person to bring that up, so I'd be open to adding that.

There are technically a few workarounds that can accomplish that, but they're not very intuitive, so a new keyword arg would be better (something like `skip_read`?). It's also possible to manually change the expiration for an existing cache item, if that's what you want to do.

**Comment by JWCook** [comment] 2022-02-21 17:05
Here's what you can currently do:

Starting with a cached response:
```python
from requests_cache import CachedSession

URL = 'https://httpbin.org/get'

session = CachedSession(expire_after=-1)
response = session.get(URL)
```

## Option 1
Manually delete the item from the cache and re-request it:
```python
session.cache.delete_url(URL)
response = session.get(URL, expire_after=360)
```

## Option 2
Use `requests` to make a non-cached request, then manually save the new response. That will override any existing cached response. Note that currently, `save_response()` only takes an absolute `datetime` object.
```python
import requests
from datetime import datetime, timedelta

response = requests.get(URL)
session.cache.save_response(response, expires=datetime.utcnow() + timedelta(seconds=360))
```

**Comment by JWCook** [comment] 2022-02-23 00:13
I made a separate issue for adding an option to skip reading from the cache: #539

I'll close this issue for now, but feel free to open a new one if you have more questions or suggestions!

**Closed by JWCook** 2022-02-23 00:13 UTC
Labels: question

**Comment by johnraz** [comment] 2022-02-24 15:18
Hey @JWCook, that's perfect! Thanks again for the time and useful answers!
