### ISSUE TITLE
Invalidate cache when the version of urllib3, requests, python or requests-cache changes

### ISSUE THREAD

**Issue by ThomasHickman** [reclosedev/requests-cache#102] opened 2018-01-06 12:21 UTC
The current versions of urllib3, requests, python and requests-cache could be stored alongside all cached requests and cached requests would be invalidated by differing versions of urllib3, requests, python and requests-cache.

**Comment by JWCook** [comment] 2021-02-25 00:45
That's not a bad idea. Perhaps a simpler way to accomplish the same thing would be to include those library version numbers in the hash (along with URL, request params, etc.) used as a cache key.

**Comment by kgk** [comment] 2021-03-24 22:19
I was bitten by this when trying out 0.6.  Was about to file a bug-report, but realized that the response object had chnaged from 0.5.2 and pickle was failing to load the previous cached responses.

**Comment by JWCook** [comment] 2021-03-24 22:27
@kgk By 0.6 do you mean the current master branch? Or the `0.6.0.dev0` pre-release build?

And yes you're right, previously cached responses won't be valid after the next release (specifically due to PR #189).

Just curious, do you have a large amount of cached data stored that you really don't want to lose? If so, it might be possible to make a script to convert it to the new format.

**Comment by kgk** [comment] 2021-03-24 22:34
Yes.. I was trying out the a build from the git source.

I did not have alot of data, but am using a long-lived redis backend which caused me to investigate for a while the issue.
Maybe just a note is needed  or a way to reset the cache programmatically (via a a command-line)..

**Comment by JWCook** [comment] 2021-03-24 22:38
You can call either `requests_cache.clear()` or `CachedSession.cache.clear()` to delete everything. But I agree that a way to just delete invalid cache items would be handy. Maybe that behavior could be added to `remove_expired_responses()` (i.e., treat invalid cache items as 'expired')?

**Comment by JWCook** [comment] 2021-03-25 03:45
Another question about this: would `major.minor` versions be sufficient? I imagine it's quite unlikely that a patch version of one of these libraries would break compatibility, and pinning requirements to the latest `major.minor` is fairly common practice. In other words, if my app pins `requests~=2.25.0`, that allows updating from `2.25.0 -> 2.25.1`, and I probably wouldn't want to invalidate all my previous cache items just because of that.

...or would I? 🤷

**Comment by JWCook** [comment] 2021-03-30 20:44
Whoops, closed this on accident.

This is now somewhat less of an issue, since any errors caused by changes in these libraries will be caught and a new response fetched. Also, #206 adds the ability to remove any invalid/broken responses with `remove_expired_responses()`.

So the remaining issue here is if a change in, say, `requests` doesn't cause errors, but changes the content or behavior of a response.

**Closed** 2021-08-15 02:24 UTC
Labels: enhancement

**Comment by JWCook** [comment] 2021-08-15 03:05
Support for custom cache keys (#360) is now included in the latest pre-release build.
* Docs: https://requests-cache.readthedocs.io/en/latest/advanced_usage.html#custom-cache-keys
* Example that accomplishes the original request for this issue: https://github.com/reclosedev/requests-cache/blob/master/examples/custom_cache_keys.py
