### ISSUE TITLE
How to migrate cache keys from 0.8.0 to 0.9.x?

### ISSUE THREAD

**Issue by kinghuang** [reclosedev/requests-cache#505] opened 2022-01-20 18:58 UTC
I upgraded from 0.8.0 to 0.9.0 and found that none of my existing filesystem cache was being used anymore. It seems the created cache keys for my requests have changed in 0.9.0.

I'd like to migrate my existing cache as it's very expensive for me to refetch everything. But, I'm having trouble understanding how the keys in 0.9.0 are created. I thought I could update the cache by reading each existing cached response, generating a new key, and saving it. So, something like this.

```python
s = CachedSession()

existing_cache_key = "6111225a1db41656"
resp = s.cache.get_response(existing_cache_key)
new_cache_key = s.cache.create_key(resp.request)
# 0.8.0 returns 6111225a1db41656
# 0.9.0 returns bf3060dbec050d72
s.cache.save_response(resp, cache_key=new_cache_key)
```

With requests-cache 0.8.0, the values of `existing_cache_key` and `new_cache_key` match. With request-cache 0.9.0, I get a new value for `new_cache_key` (`bf3060dbec050d72`).

But, when I subsequently do `s.get(resp.request.url)` with 0.9.0, a different cache key is generated (`0e0407e56878a2df`) and a new cached response is created. If I read in the new cache file and create a key from its request, I get back the other key (`bf3060dbec050d72`).

```python
existing_cache_key = "0e0407e56878a2df"
resp = s.cache.get_response(existing_cache_key)
cache_key = s.cache.create_key(resp.request)
# 0.9.0 returns bf3060dbec050d72
```

There's obviously some detail I'm missing in how 0.9.0 calculates cache keys. How do I correctly create cache keys with 0.9.0 so that I can convert my 0.8.0 cache to work with 0.9.0?

**Comment by JWCook** [comment] 2022-01-23 15:58
As you've found, cache keys are likely to change across requests-cache versions, because new features related to request matching will affect how cache keys are generated.

Here's an example that I think will do what you want. This will create a new cache in case something goes wrong and you want to keep your old one as a backup:
```python
from requests_cache import CachedSession

session1 = CachedSession()  # Old cache created with a previous requests-cache version
session2 = CachedSession('new_cache')  # New cache created with the current requests-cache version

for response in session1.cache.values():
    session2.cache.save_response(response)
```

There are a number of reasons why `s.get(resp.request.url)` might potentially generate a different key than `s.cache.create_key(resp.request)`, which depends on any other request details (headers, parameters, etc.). Some `CachedSession` settings can affect this as well.

Let me know if the above example works for you. If not, we can take a closer look at your specific requests and why they might be not matching.

**Comment by kinghuang** [comment] 2022-02-02 05:39
Thanks for the info. The code you posted is basically how I've moved cached responses around in 0.8.x. If I follow the code exactly with 0.9.1, the new cache doesn't save the responses with the same key that's generated making a full request.

After some trial and error, it seems the crucial element are the extra `kwargs` passed to `create_key` in [CacheMixin.send()](https://github.com/reclosedev/requests-cache/blob/d9419964120226cf63ee08e6434609c39f70856c/requests_cache/session.py#L117). I have to make sure to pass in exactly what `requests` generates in order to get the right key. I've resorted to matching part of the implementation of [Session.request()](https://github.com/psf/requests/blob/24dfbfde552bb8ce48eec415714cbe793cfa95bd/requests/sessions.py#L457) to get the right result.

```python
from requests.models import Request
from requests_cache.backends.filesystem import FileCache

session1 = CachedSession()  # Old cache created with a previous requests-cache version
session2 = CachedSession('new_cache')  # New cache created with the current requests-cache version

for response in session1.cache.values():
    url = resp.request.url
    req = Request(method="GET", url=url)
    prep = session2.prepare_request(req)

    settings = session2.merge_environment_settings(prep.url, None, None, None, None)
    send_kwargs = {
        "timeout": None,
        "allow_redirects": True,
    }
    send_kwargs.update(settings)

    cache_key = session2.cache.create_key(prep, **send_kwargs)

    session2.cache.save_response(resp, cache_key=cache_key)
```

**Comment by kinghuang** [comment] 2022-02-03 01:17
Weird! I'll dig into this some more when I have time to narrow down what exactly in `send_kwargs` is causing the different keys for me. I'm not passing any extra arguments when I make requests, so I'm not sure why it makes a difference for me.

**Comment by JWCook** [comment] 2022-02-03 16:49
Something that may help in debugging is to locally modify this section:
https://github.com/reclosedev/requests-cache/blob/aafc42f7198d2517efda03d56ae3eeeb7ff85201/requests_cache/cache_keys.py#L55-L67

Into something that incrementally prints out the key as it's being made, for example:
```python
    key_parts = {
        'method': request.method or '',
        'url (including params)': request.url,
        'body': request.body or '',
        'verify': request_kwargs.get('verify', True),
    }

    # Debug: print key incrementally after applying each key part
    key = blake2b(digest_size=8)
    for label, part in key_parts.items():
        key.update(encode(part))
        print(f'{label}: {key.hexdigest()}')
    for part in get_matched_headers(request.headers, match_headers):
        key.update(encode(part))
        print(f'headers: {key.hexdigest()}')

    return key.hexdigest()
```

That should help narrow down which piece is creating a different hash.

**Comment by JWCook** [comment] 2022-03-11 14:59
@kinghuang Were you able to run the debugging example above, and did that provide any clues?

**Comment by kinghuang** [comment] 2022-03-13 17:30
I did find a difference with a frozen dict vs a normal dict. I haven't touched this in a bit, but I might have a dev joining soon to help.

**Comment by JWCook** [comment] 2022-04-12 03:18
I will close this issue for now since I'm not able to reproduce, but do let me know if you find out any more about this, and I can reopen if needed.

**Closed by JWCook** 2022-04-12 03:18 UTC
Labels: question, help-wanted
